pre-commit:
  commands:
    clean:
      files: git ls-files
      glob: '*.ipynb'
      run: uv run jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
    format:
      files: git ls-files
      glob: '*.py'
      run: ruff format {staged_files}
      stage_fixed: true
    check:
      files: git ls-files
      glob: '*.py'
      run: ruff check {staged_files} --fix